### PR TITLE
Transferred `duplicate()` to tidyplus

### PR DESCRIPTION
**Pull request by dunkenwg**
- Moved `duplicate()` and its tests to tidyplus
- Rebuilt package and updated documentation

### CODE REVIEW

**Review by aylapear — APPROVED** [review]
This looks good. Thanks

**Review by joethorley — CHANGES_REQUESTED** [review]
This is a great idea. But to reduce pain for users I think we should merely soft deprecate it at this time for tidyplus::duplicates(). I'm happy to go through how to do that.

**Comment by dunkenwg** [comment]
Did not add:
```
test_that("ps_duplicates() gives deprecation message", {
  expect_warning(
    ps_duplicates(data.frame(x = 1:2, y = 1:2)),
    regexp = "was deprecated"
  )
})
```
as warnings are only issued once every 8 hours. This test will fail unless it is the first time `ps_duplicates()` has been called in 8 hours.

**Review by joethorley — CHANGES_REQUESTED** [review]
Good work.

See the following on how to test that it has been deprecated

https://lifecycle.r-lib.org/reference/verbosity.html

**Comment by dunkenwg** [comment]
Thanks @joethorley! The tests should be good to go now.

**Review by joethorley — APPROVED** [review]
looks great!

**Comment by dunkenwg** [comment]
No worries!

**Pull request merged**
